"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _d2I18n = _interopRequireDefault(require("@dhis2/d2-i18n"));

var _moment = _interopRequireDefault(require("moment"));

var _translations = _interopRequireDefault(require("./en/translations.json"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var namespace = 'ui-widgets';

_moment.default.locale('en');

_d2I18n.default.addResources('en', namespace, _translations.default);

_d2I18n.default.setDefaultNamespace(namespace);

_d2I18n.default.changeLanguage('en');

var _default = _d2I18n.default;
exports.default = _default;